// <auto-generated />
using Covid_Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Covid_Api.Migrations
{
    [DbContext(typeof(CovidAppContext))]
    [Migration("20220211125318_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("Covid_Api.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("Covid_Api.Models.DailyData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveCases")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CasesPer1MPopulation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Serious")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalDeaths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRecovered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("dailyDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
